server:
  port: 8084
  
spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/empdb?useSSL=false
    username: root
    password: Chola@65
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    