
server:
  port: 8082

spring:
  application:
    name: patients managemnet

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      

resilience4j:
  circuitbreaker:
    instances:
      servicesDetails:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 80
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
        
      details:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 80
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based   
        